config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :inventory_items
  resources :locations, except: [:show]

  root controller: :inventory_items, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  # We'll allow items not to have a location set.
  has_many :item_stocks, dependent: :destroy
  accepts_nested_attributes_for :item_stocks

  validates :name, presence: true

  # Determines the total stock quantity for this item.
  def total_quantity
    item_stocks.sum(:quantity)
  end

  # Gets the number of locations that this item is available at.
  def num_locations_available
    item_stocks.where('quantity > 0').count
  end

  # Gets an ItemStock object for each location, regardless if one actually exists.
  def all_stocks
    item_stocks.select([
      'item_stocks.id',
      'l.id AS location_id',
      'CASE WHEN item_stocks.quantity IS NULL THEN 0 ELSE item_stocks.quantity END AS quantity',
      'item_stocks.created_at',
      'item_stocks.updated_at',
    ])
      .from(ActiveRecord::Base.sanitize_sql_array(["(SELECT * FROM item_stocks WHERE inventory_item_id = ?) AS item_stocks", self.id]))
      .joins('RIGHT OUTER JOIN locations AS l ON location_id = l.id OR location_id IS NULL')
      # Remove the default where clause, which filters by inventory_item_id which we've already done
      .unscope(:where)
  end
end

app/models/item_stock.rb
# Ties an inventory item to a location, with a quantity present at that location.
class ItemStock < ApplicationRecord
  belongs_to :location
  belongs_to :inventory_item

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :item_stocks, dependent: :destroy
    accepts_nested_attributes_for :item_stocks

    validates :name, presence: true

    # Gets the number of different items that are in stock at this location
    def num_unique_items
        self.item_stocks.where('quantity > 0').count
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Disable CSRF protection, since we're expecting client API users.
  protect_from_forgery with: :null_session
end

app/controllers/concerns/item_utils.rb
require "active_support/concern"

module ItemUtils
  extend ActiveSupport::Concern

  def current_item
    id = params[:inventory_item_id] || params[:id]
    @item ||= InventoryItem.find_by(id: id)
    render status: :not_found, plain: "Item #{id} not found" if @item.blank?
    @item
  end
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  include ItemUtils
  before_action :current_item, only: [:edit, :show, :update, :destroy]

  def index
    respond_to do |format|
      format.html do
        @items = InventoryItem.all
      end
      format.json { render json: InventoryItem.all.to_json(methods: [:total_quantity]) }
    end
  end

  def new
    @item = InventoryItem.new
  end

  def create
    item = InventoryItem.create!(inventory_item_params)
    respond_to do |format|
      format.html { redirect_to action: :index }
      format.json { render json: item, status: :created }
    end
  rescue StandardError => validation_errs
    render plain: validation_errs.message # TODO not sure about .message
  end

  def show
    respond_to do |format|
      format.html { redirect_to action: :edit }
      format.json do
        render json: current_item.to_json(include: [:item_stocks])
      end
    end
  end

  def edit
    @item = current_item
  end

  def update
    ActiveRecord::Base.transaction do
      current_item.update!(inventory_item_params.except(:item_stocks_attributes))
      if (stocks = inventory_item_params[:item_stocks_attributes]).present?
        stocks = stocks.send(stocks.is_a?(Array) ? 'map' : 'transform_values') { |stock| { **stock, inventory_item_id: current_item.id } }
        stocks = stocks.values if stocks.is_a?(ActionController::Parameters)
        # Validations get skipped here unfortunately
        ItemStock.upsert_all(
          stocks,
          # The order of the indexed columns here must match the declaration order of the migration.
          unique_by: [:location_id, :inventory_item_id],
          update_only: [:quantity],
          record_timestamps: true,
        )
      end
    end
    respond_to do |format|
      format.html { redirect_to action: :index }
      format.json { render json: current_item.to_json(include: [:item_stocks]) }
    end
  rescue StandardError => err
    render status: :internal_server_error, plain: err
  end

  def destroy
    current_item.destroy!
    respond_to do |format|
        format.html { redirect_to action: :index }
        format.json { head :ok }
    end
  end

  private

  def inventory_item_params
    params.require(:inventory_item).permit(
      :name,
      item_stocks_attributes: [:quantity, :location_id],
    )
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    respond_to do |format|
      format.html { @locations = Location.all }
      format.json { render json: Location.all }
    end
  end

  def create
    location = Location.new(location_params)
    if location.save
        respond_to do |format|
            format.html { redirect_to action: :index }
            format.json { render json: location, status: :created }
        end
    else
        render plain: location.errors, status: :unprocessable_entity
    end
  end

  def new
    @location = Location.new
  end

  def edit
    @location = current_location
  end

  def update
    current_location.update!(location_params)
    respond_to do |format|
      format.html { redirect_to action: :index }
      format.json { render status: :ok, json: current_location }
    end
  rescue StandardError => e
    render status: :internal_server_error, plain: e
  end

  def destroy
    current_location.destroy!
    respond_to do |format|
        format.html { redirect_to action: :index }
        format.json { head :ok }
    end
  end

  private

  def location_params
    params.require(:location).permit(:name)
  end

  def current_location
    id = params[:id]
    @location ||= Location.find_by(id: id)
    render status: :not_found, plain: "Location #{id} not found" if @location.blank?
    @location
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/item_stocks_helper.rb
module ItemStocksHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/inventory_items/_edit_form.html.erb
<%= form_with model: @item do |form| %>
    <h1><%= title %> Inventory Item</h1>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <%= yield form %>
    <p>
        <%= form.submit 'Submit' %>
    </p>
<% end %>

app/views/inventory_items/edit.html.erb
<%= render 'edit_form', title: 'Edit' do |form| %>
    <h2>Location Stock</h2>
    <% @item.all_stocks.includes(:location).each do |stock| %>
        <%= form.fields_for :item_stocks, stock do |fields| %>
            <%= fields.label :quantity, stock.location.name %>
            <%= fields.number_field :quantity, min: 0 %>
            <%= fields.number_field :location_id, hidden: true %>
        <% end %>
        <br/>
    <% end %>
<% end %>

<%
=begin%>
  Useful: https://api.rubyonrails.org/v7.0/classes/ActionView/Helpers/FormHelper.html#method-i-fields_for
<%
=end%>

app/views/inventory_items/index.html.erb
<h1>Inventory Items</h1>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Total Stock</th>
            <th>Locations</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @items.each do |item| %>
            <tr>
                <td><%= item.id %></td>
                <td><%= item.name %></td>
                <td><%= item.total_quantity %></td>
                <td><%= item.num_locations_available %></td>
                <td><%= link_to 'Edit', edit_inventory_item_path(item.id), method: :get %></td>
                <td><%= link_to 'Delete', item, method: :delete %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/inventory_items/new.html.erb
<%= render 'edit_form', title: 'New' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kyle Anderson - Shopify Challenge Summer 2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <br/>

  <footer>
    <%= render '/nav_links' %>
  </footer>
</html>

app/views/locations/_edit_form.html.erb
<%= form_with model: @location do |form| %>
    <h1><%= title %> Location</h1>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
    <p>
        <%= form.submit 'Submit' %>
    </p>
<% end %>

app/views/locations/edit.html.erb
<%= render 'edit_form', title: 'Edit' %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<table>
    <thead>
        <th>Id</th>
        <th>Name</th>
        <th>Number of items</th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
        <% @locations.each do |location| %>
            <tr>
                <td><%= location.id %></td>
                <td><%= location.name %></td>
                <td><%= location.num_unique_items %></td>
                <td><%= link_to 'Edit', edit_location_path(location.id) %>
                <td><%= link_to 'Delete', location, method: :delete %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/locations/new.html.erb
<%= render 'edit_form', title: 'New' %>